version: "3.8"

services:
  mysql:
    image: mysql:8.0.31
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${APP_PORT}
    depends_on:
      - mysql
    ports:
      - ${APP_PORT}:${APP_PORT}
